[package]
name = "haf_ec_service"
categories = [ "embedded", "no-std" ]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Provides standard EC services to OS"
readme = "README.md"
keywords = [ "embedded", "no-std", "boot", "firmware" ]
repository = "https://github.com/OpenDevicePartnership/haf_ec_service"
rust-version = "1.81"

[package.metadata.docs.rs]
targets = [
    "aarch64-unknown-none",
    "aarch64-unknown-none-softfloat",
]

[dependencies]
aarch64-cpu = "9.4.0"
ffa = { git = "https://github.com/OpenDevicePartnership/ffa", rev = "1f6ef264"}
uuid = { version = "1.0", default-features = false, features = ["v1"] }

