[workspace]
resolver = "2"
members = [ "ec-sp",
	"xtask"
]

[workspace.package]
authors = [ "Felipe Balbi <febalbi@microsoft.com>" ]
categories = [ "embedded", "no-std" ]
version = "0.1.0"
edition = "2021"
keywords = [ "embedded", "no-std", "boot", "firmware" ]
repository = "https://github.com/pop-project/haf_ec_service"
rust-version = "1.81"

[workspace.dependencies]
aarch64-cpu = "9.4.0"
ffa = "0.1"

[patch.crates-io]
#ffa = { git = "https://github.com/pop-project/ffa" }
ffa = { path = "/home/phil/github/ffa" }

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true
panic = "abort"

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false
panic = "abort"
